export const reviews = [
  {
    id: 1,
    name: "María Rodríguez",
    city: "Buenos Aires",
    review:
      "Una experiencia maravillosa. La cabaña estaba impecable, con todas las comodidades y una vista espectacular. Definitivamente volveremos.",
    image: "/avatars/avatar1.png",
  },
  {
    id: 2,
    name: "Carlos Méndez",
    city: "Córdoba",
    review:
      "El lugar perfecto para desconectar. La atención fue excelente, la cabaña muy cómoda y la zona es hermosa para hacer caminatas.",
    image: "/avatars/avatar2.png",
  },
  {
    id: 3,
    name: "Laura y Diego",
    city: "Rosario",
    review:
      "Celebramos nuestro aniversario en la cabaña El Roble y fue mágico. El jacuzzi con vista al bosque y la chimenea crearon el ambiente perfecto.",
    image: "/avatars/avatar3.png",
  },
  {
    id: 4,
    name: "Sofía Pérez",
    city: "Mendoza",
    review:
      "Hermoso lugar, rodeado de naturaleza. El personal muy atento y las instalaciones de primera. ¡Recomendado!",
    image: "/avatars/avatar4.png",
  },
  {
    id: 5,
    name: "Martín López",
    city: "Bariloche",
    review:
      "Las cabañas superaron nuestras expectativas. Volveremos en invierno para disfrutar de la chimenea y la nieve.",
    image: "/avatars/avatar5.png",
  },
];

export const bentoGalleryItems = [
  {
    id: 1,
    title: "Cabaña El Pinar",
    description: "Vista al bosque, chimenea y deck privado.",
    size: "large",
    image: "https://v0.dev/placeholder.svg?height=600&width=600",
    span: "col-span-2 row-span-2",
  },
  {
    id: 2,
    title: "Cabaña El Roble",
    description: "Ideal para familias, terraza y parrilla.",
    size: "medium",
    image: "https://v0.dev/placeholder.svg?height=300&width=600",
    span: "col-span-2 row-span-1",
  },
  {
    id: 3,
    title: "Cabaña El Valle",
    description: "Jacuzzi, vista panorámica y lujo rústico.",
    size: "medium",
    image: "https://v0.dev/placeholder.svg?height=600&width=300",
    span: "col-span-1 row-span-2",
  },
  {
    id: 4,
    title: "Atardecer en la montaña",
    description: "Colores únicos y tranquilidad absoluta.",
    size: "small",
    image: "https://v0.dev/placeholder.svg?height=300&width=300",
    span: "col-span-1 row-span-1",
  },
  {
    id: 5,
    title: "Río cercano",
    description: "A pasos de la naturaleza y el agua.",
    size: "small",
    image: "https://v0.dev/placeholder.svg?height=300&width=300",
    span: "col-span-1 row-span-1",
  },
  {
    id: 6,
    title: "Senderos y aventura",
    description: "Caminatas y actividades al aire libre.",
    size: "medium",
    image: "https://v0.dev/placeholder.svg?height=300&width=600",
    span: "col-span-2 row-span-1",
  },
  {
    id: 7,
    title: "Desayuno campestre",
    description: "Productos locales y vistas increíbles.",
    size: "medium",
    image: "https://v0.dev/placeholder.svg?height=600&width=300",
    span: "col-span-1 row-span-2",
  },
  {
    id: 8,
    title: "Noche estrellada",
    description: "Cielos limpios y fogón bajo las estrellas.",
    size: "small",
    image: "https://v0.dev/placeholder.svg?height=300&width=300",
    span: "col-span-1 row-span-1",
  },
  {
    id: 9,
    title: "Cabaña La Cascada",
    description: "Cerca de un arroyo y rodeada de árboles.",
    size: "medium",
    image: "https://v0.dev/placeholder.svg?height=300&width=600",
    span: "col-span-2 row-span-1",
  },
  {
    id: 10,
    title: "Mirador del Valle",
    description: "Vistas panorámicas y terraza amplia.",
    size: "large",
    image: "https://v0.dev/placeholder.svg?height=600&width=600",
    span: "col-span-2 row-span-2",
  },
  {
    id: 11,
    title: "Cabaña El Refugio",
    description: "Ambiente cálido y decoración rústica.",
    size: "small",
    image: "https://v0.dev/placeholder.svg?height=300&width=300",
    span: "col-span-1 row-span-1",
  },
  {
    id: 12,
    title: "Bosque Encantado",
    description: "Senderos privados y mucha sombra.",
    size: "medium",
    image: "https://v0.dev/placeholder.svg?height=600&width=300",
    span: "col-span-1 row-span-2",
  },
  {
    id: 13,
    title: "Cabaña del Lago",
    description: "A orillas del lago, con muelle propio.",
    size: "medium",
    image: "https://v0.dev/placeholder.svg?height=300&width=600",
    span: "col-span-2 row-span-1",
  },
  {
    id: 14,
    title: "Amanecer Serrano",
    description: "Despierta con el sol entre las sierras.",
    size: "small",
    image: "https://v0.dev/placeholder.svg?height=300&width=300",
    span: "col-span-1 row-span-1",
  },
  {
    id: 15,
    title: "Cabaña El Nogal",
    description: "Rodeada de nogales y aire puro.",
    size: "medium",
    image: "https://v0.dev/placeholder.svg?height=600&width=300",
    span: "col-span-1 row-span-2",
  },
  {
    id: 16,
    title: "Fogón y Estrellas",
    description: "Ideal para noches de fogata y charla.",
    size: "small",
    image: "https://v0.dev/placeholder.svg?height=300&width=300",
    span: "col-span-1 row-span-1",
  },
]; 